[package]
name = "vmtest"
authors = ["Daniel Xu <dxu@dxuuu.xyz>"]
description = "Helps run your tests in virtual machines"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.26", features = ["derive"] }
serde = "1.0.147"
serde_derive = "1.0.147"
toml = "0.5.9"
